# Generated by Django 5.1.2 on 2024-12-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_books', '0004_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
