# Generated by Django 5.1.2 on 2024-12-21 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_books', '0005_books_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('can_change_order', 'Can change order'), ('can_delete_order', 'Can delete order'), ('can_view_order', 'Can view order')]},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'permissions': [('can_add_order_item', 'Can add order item'), ('can_change_order_item', 'Can change order item'), ('can_delete_order_item', 'Can delete order item'), ('can_view_order_item', 'Can view order item')]},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'permissions': [('can_add_shipping_address', 'Can add shipping address'), ('can_change_shipping_address', 'Can change shipping address'), ('can_delete_shipping_address', 'Can delete shipping address'), ('can_view_shipping_address', 'Can view shipping address')]},
        ),
    ]
