# Generated by Django 5.1.2 on 2024-12-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_profile_address_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='postal_code',
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
    ]
