# Generated by Django 5.1.2 on 2024-12-21 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_alter_profile_postal_code_alter_profile_telephone'),
        ('app_users', '0006_create_order_manager_group'),
    ]

    operations = [
    ]
